version: '3.7'
services:
  integration-test:
    container_name: integration-test
    build:
      context: backend
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://declutter_me:p4ssw0rd@postgres:5432/declutter_me_test"
    volumes:
      - ./backend:/backend
    command: |
      ./wait-for-it.sh postgres:5432 -t 120 --
      npm run test:integration
